### ISSUE TITLE
Release new version with `syn` v2

### ISSUE THREAD

**Issue by daxpedda** [zesterer/pollster#25]
Would be great to get a new release including the update to `syn` v2.

See #18.

**Comment by zesterer** [comment]
I'll try to find time to do this over the next few days. Thanks for the reminder!

**Comment by daxpedda** [comment]
@zesterer friendly ping.

**Comment by zesterer** [comment]
Version 0.4.0 has been released (`pollster-macro` and `pollster` now both use the same version number).

**Comment by daxpedda** [comment]
Unfortunately `pollster` itself still depends on `pollster-macro` v0.1.
So `pollster` itself needs an update as well.

**Comment by zesterer** [comment]
Eurgh, drat. I'll fix that tonight. Must have been half asleep!

**Comment by zesterer** [comment]
Published!
